---
title: "Bibliografía"
---

# Contenido temático  

1. Sistemas de ecuaciones lineales 
    - 1.1 Sistemas lineales 
    - 1.2 Métodos de solución: sustitución, igualación, eliminación y método gráfico 
    - 1.3 Ejercicios y problemas en economía 
2. Matrices 
    - 2.1 Definición de matriz 
    - 2.2 Propiedades de una matriz 
    - 2.3 Operaciones con matrices 
    - 2.4 Solución de SEL con Gauss-Jordan 
3. Vectores 
    - 3.1 Propiedades de los vectores  
    - 3.2 Producto punto 
4. Determinantes 
    - 4.1 El paralelogramo 
    - 4.2 Propiedades de los determinantes 
    - 4.3 Solución de SEL con regla de Cramer 
5. La matriz inversa 
    - 5.1 Definición  
    - 5.2 Solución de SEL por el método de la matriz inversa 
6. Aplicaciones en Economía

# Bibliografía

* Kolman, Bernard & Hill, David R.. (2006) Álgebra lineal. 8va. Edición Ed. Pearson Educación, México. 

* Grossman, Stanley I.. (1980) Elementary Linear Algebra, International Student Edition. 

* Grossman, Stanley I.. (1993) Álgebra lineal con aplicaciones. 4a edición. Ed. Mc. Graw-Hill. México D.F. 

* Aleskerov, F. T., Ersel, H., & Piontkovski, D. (2011). Linear algebra for economists. Springer Verlag. 

* Anton, H., & Rorres, C. (2014). Elementary linear álgebra: applications version (11th edition). Wiley. 

* Stewart, J., María del Carmen Rodríguez Pedroza, & Stewart, J. (2013).Cálculo de una variable: trascendentes tempranas(Séptima edición). Cengage Learning. 

* Lipschutz, S., Martinez Ontalba, C., & Lipschutz, S. (1992).Algebra lineal (2nd ed.). McGraw-Hill. 

* Simon, Carl P. & Blume, Lawrence. Mathematics for Economists.  

* Chiang, Alpha C. & Wainwright, Kevin. Fundamental Methods of Mathematical Economics. 


::: {.text-center}
[{{< fa brands google-drive >}} Material en Google Drive](https://drive.google.com/drive/folders/1R520muedEOY9bfZ5AiDWSgZtLN6KmGby){.btn .btn-primary .btn-lg .btn-flotante}
:::