---
title: "Tarea 01"
author: "Eduardo Castro; Marvin Trejo"
date: "2026-09-11"
categories: [Tarea, 2027-I]
---

# A)

Partiendo de las siguientes funciones de oferta ($Q_S$) y demanda ($Q_D$), determina el precio y cantidad de equilibrio por el **método de Gauss-Jordan**.

## A.1)

$$
\begin{aligned}
Q_D &= 30 -4P \\
Q_S &= 11+3P\\
\end{aligned}
$$

Primero reacomodamos las variables:

$$
\begin{aligned}
Q+4P &= 30 \\
Q-3P &= 11\\
\end{aligned}
\implies
\underbrace{
\left[ 
\begin{array}{cc|c}
1 & 4 & 30 \\
1 & -3 & 11
\end{array} 
\right]}
_{\text{A}}
$$

Verificamos que el sistema tenga solución única calculando el determinante:

$$
\begin{aligned}
|A| &= 1 \cdot -3 - (4 \cdot 1) \\
|A| &= -3 - 4 = -7
\end{aligned}
$$

Dado que $|A| \neq 0$ el sistema tiene solución única. Procedemos a resolver:

$$
\left[
\begin{array}{cc|c}
1 & 4 & 30 \\
1 & -3 & 11
\end{array}
\right]
\;\;\xrightarrow{F_2=F_2-F_1}\;\;
\left[
\begin{array}{cc|c}
1 & 4 & 30 \\
0 & -7 & -19
\end{array}
\right]
$$

$$
\left[
\begin{array}{cc|c}
1 & 4 & 30 \\
0 & -7 & -19
\end{array}
\right]
\;\;\xrightarrow{F_2=-\tfrac{1}{7}F_2}\;\;
\left[
\begin{array}{cc|c}
1 & 4 & 30 \\
0 & 1 & \frac{19}{7}
\end{array}
\right]
$$

$$
\left[
\begin{array}{cc|c}
1 & 4 & 30 \\
0 & 1 & \frac{19}{7}
\end{array}
\right]
\;\;\xrightarrow{F_1=F_1-4F_2}\;\;
\left[
\begin{array}{cc|c}
1 & 0 & \frac{134}{7} \\
0 & 1 & \frac{19}{7}
\end{array}
\right]
$$

**Solución** 

$$ 
\left[ 
\begin{array}{cc|c}
1 & 0 & \frac{134}{7} \\
0 & 1 & \frac{19}{7}
\end{array} 
\right]
\implies
\begin{array}{cc|c}
Q=\frac{134}{7} \\
P=\frac{19}{7}
\end{array} 
$$

## A.2)

$$
\begin{aligned}
Q_D &= 35 -5P \\
Q_S &= 14+4P\\
\end{aligned}
$$

Acomodamos las variables ($Q = Q_D = Q_S$):

$$
\begin{aligned}
Q+5P &= 35 \\
Q-4P &= 14\\
\end{aligned}
\implies
\underbrace{
\left[ 
\begin{array}{cc|c}
1 & 5 & 35 \\
1 & -4 & 14
\end{array} 
\right]}
_{\text{A}}
$$

Calculamos el determinante:

$$
\begin{aligned}
|A| &= 1 \cdot -4 - (5 \cdot 1) \\
|A| &= -4 - 5 = -9
\end{aligned}
$$

Dado que $|A| \neq 0$ el sistema tiene solución única.

$$
\left[
\begin{array}{cc|c}
1 & 5 & 35 \\
1 & -4 & 14
\end{array}
\right]
\;\;\xrightarrow{F_2=F_2-F_1}\;\;
\left[
\begin{array}{cc|c}
1 & 5 & 35 \\
0 & -9 & -21
\end{array}
\right]
$$

$$
\left[
\begin{array}{cc|c}
1 & 5 & 35 \\
0 & -9 & -21
\end{array}
\right]
\;\;\xrightarrow{F_2=-\tfrac{1}{9}F_2}\;\;
\left[
\begin{array}{cc|c}
1 & 5 & 35 \\
0 & 1 & \frac{7}{3}
\end{array}
\right]
$$

$$
\left[
\begin{array}{cc|c}
1 & 5 & 35 \\
0 & 1 & \frac{7}{3}
\end{array}
\right]
\;\;\xrightarrow{F_1=F_1-5F_2}\;\;
\left[
\begin{array}{cc|c}
1 & 0 & \frac{70}{3} \\
0 & 1 & \frac{7}{3}
\end{array}
\right]
$$

**Solución** 

$$ 
\left[ 
\begin{array}{cc|c}
1 & 0 & \frac{70}{3} \\
0 & 1 & \frac{7}{3}
\end{array} 
\right]
\implies
\begin{array}{cc|c}
Q=\frac{70}{3} \\
P=\frac{7}{3}
\end{array} 
$$

# B)

Calcula el determinante de los siguientes sistemas de ecuaciones lineales y encuentra la solución por el **método de Gauss-Jordan**.

## B.1)

$$
\begin{aligned}
2x+y-z&=3 \\
x-y+2z&=5\\
3x+2y&=8-z
\end{aligned}
$$

Primero, reacomodamos la tercera ecuación para alinear las variables:

$$
\begin{aligned}
2x+y-z&=3 \\
x-y+2z&=5\\
3x+2y+z&=8
\end{aligned}
\implies
\underbrace{
\left[ 
\begin{array}{ccc|c}
2 & 1 & -1 & 3 \\
1 & -1 & 2 & 5 \\
3 & 2 & 1 & 8
\end{array} 
\right]}
_{\text{A}}
$$

Calculamos el determinante de la matriz A:

$$
\begin{aligned}
|A| &= 2(-1 \cdot 1 - 2 \cdot 2) - 1(1 \cdot 1 - 2 \cdot 3) + (-1)(1 \cdot 2 - (-1) \cdot 3) \\
|A| &= 2(-1-4) - 1(1-6) - 1(2+3) \\
|A| &= 2(-5) - 1(-5) - 1(5) \\
|A| &= -10 + 5 - 5 = -10
\end{aligned}
$$

Dado que $|A| \neq 0$, el sistema tiene solución única. Procedemos con Gauss-Jordan intercambiando $F_1$ y $F_2$ para facilitar los cálculos:

$$
\left[ 
\begin{array}{ccc|c}
2 & 1 & -1 & 3 \\
1 & -1 & 2 & 5 \\
3 & 2 & 1 & 8
\end{array} 
\right]
\;\;\xrightarrow{F_1 \leftrightarrow F_2}\;\;
\left[ 
\begin{array}{ccc|c}
1 & -1 & 2 & 5 \\
2 & 1 & -1 & 3 \\
3 & 2 & 1 & 8
\end{array} 
\right]
$$

$$
\left[ 
\begin{array}{ccc|c}
1 & -1 & 2 & 5 \\
2 & 1 & -1 & 3 \\
3 & 2 & 1 & 8
\end{array} 
\right]
\;\;\xrightarrow{F_2=F_2-2F_1}\;\;
\left[ 
\begin{array}{ccc|c}
1 & -1 & 2 & 5 \\
0 & 3 & -5 & -7 \\
3 & 2 & 1 & 8
\end{array} 
\right]
$$

$$
\left[ 
\begin{array}{ccc|c}
1 & -1 & 2 & 5 \\
0 & 3 & -5 & -7 \\
3 & 2 & 1 & 8
\end{array} 
\right]
\;\;\xrightarrow{F_3=F_3-3F_1}\;\;
\left[ 
\begin{array}{ccc|c}
1 & -1 & 2 & 5 \\
0 & 3 & -5 & -7 \\
0 & 5 & -5 & -7
\end{array} 
\right]
$$

$$
\left[ 
\begin{array}{ccc|c}
1 & -1 & 2 & 5 \\
0 & 3 & -5 & -7 \\
0 & 5 & -5 & -7
\end{array} 
\right]
\;\;\xrightarrow{F_2=\tfrac{1}{3}F_2}\;\;
\left[ 
\begin{array}{ccc|c}
1 & -1 & 2 & 5 \\
0 & 1 & -\frac{5}{3} & -\frac{7}{3} \\
0 & 5 & -5 & -7
\end{array} 
\right]
$$

$$
\left[ 
\begin{array}{ccc|c}
1 & -1 & 2 & 5 \\
0 & 1 & -\frac{5}{3} & -\frac{7}{3} \\
0 & 5 & -5 & -7
\end{array} 
\right]
\;\;\xrightarrow{F_3=F_3-5F_2}\;\;
\left[ 
\begin{array}{ccc|c}
1 & -1 & 2 & 5 \\
0 & 1 & -\frac{5}{3} & -\frac{7}{3} \\
0 & 0 & \frac{10}{3} & \frac{14}{3}
\end{array} 
\right]
$$

$$
\left[ 
\begin{array}{ccc|c}
1 & -1 & 2 & 5 \\
0 & 1 & -\frac{5}{3} & -\frac{7}{3} \\
0 & 0 & \frac{10}{3} & \frac{14}{3}
\end{array} 
\right]
\;\;\xrightarrow{F_3=\tfrac{3}{10}F_3}\;\;
\left[ 
\begin{array}{ccc|c}
1 & -1 & 2 & 5 \\
0 & 1 & -\frac{5}{3} & -\frac{7}{3} \\
0 & 0 & 1 & \frac{7}{5}
\end{array} 
\right]
$$

$$
\left[ 
\begin{array}{ccc|c}
1 & -1 & 2 & 5 \\
0 & 1 & -\frac{5}{3} & -\frac{7}{3} \\
0 & 0 & 1 & \frac{7}{5}
\end{array} 
\right]
\;\;\xrightarrow{F_1=F_1+F_2}\;\;
\left[ 
\begin{array}{ccc|c}
1 & 0 & \frac{1}{3} & \frac{8}{3} \\
0 & 1 & -\frac{5}{3} & -\frac{7}{3} \\
0 & 0 & 1 & \frac{7}{5}
\end{array} 
\right]
$$

$$
\left[ 
\begin{array}{ccc|c}
1 & 0 & \frac{1}{3} & \frac{8}{3} \\
0 & 1 & -\frac{5}{3} & -\frac{7}{3} \\
0 & 0 & 1 & \frac{7}{5}
\end{array} 
\right]
\;\;\xrightarrow{F_2=F_2+\tfrac{5}{3}F_3}\;\;
\left[ 
\begin{array}{ccc|c}
1 & 0 & \frac{1}{3} & \frac{8}{3} \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & \frac{7}{5}
\end{array} 
\right]
$$

$$
\left[ 
\begin{array}{ccc|c}
1 & 0 & \frac{1}{3} & \frac{8}{3} \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & \frac{7}{5}
\end{array} 
\right]
\;\;\xrightarrow{F_1=F_1-\tfrac{1}{3}F_3}\;\;
\left[ 
\begin{array}{ccc|c}
1 & 0 & 0 & \frac{11}{5} \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & \frac{7}{5}
\end{array} 
\right]
$$

**Solución** 

$$ 
\left[ 
\begin{array}{ccc|c}
1 & 0 & 0 & \frac{11}{5} \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & \frac{7}{5}
\end{array} 
\right]
\implies
\begin{array}{cc|c}
x=\frac{11}{5} \\
y=0 \\
z=\frac{7}{5}
\end{array} 
$$

## B.2)

$$
\begin{aligned}
x+y-z&=2 \\
x-y+2z&=0\\
-x+2y+10z&=1
\end{aligned}
\implies
\underbrace{
\left[ 
\begin{array}{ccc|c}
1 & 1 & -1 & 2 \\
1 & -1 & 2 & 0 \\
-1 & 2 & 10 & 1
\end{array} 
\right]}
_{\text{A}}
$$

Calculamos el determinante:

$$
\begin{aligned}
|A| &= 1(-1 \cdot 10 - 2 \cdot 2) - 1(1 \cdot 10 - 2 \cdot -1) + (-1)(1 \cdot 2 - (-1) \cdot -1) \\
|A| &= 1(-10-4) - 1(10+2) - 1(2-1) \\
|A| &= 1(-14) - 1(12) - 1(1) \\
|A| &= -14 - 12 - 1 = -27
\end{aligned}
$$

Dado que $|A| \neq 0$, procedemos a resolver:

$$
\left[ 
\begin{array}{ccc|c}
1 & 1 & -1 & 2 \\
1 & -1 & 2 & 0 \\
-1 & 2 & 10 & 1
\end{array} 
\right]
\;\;\xrightarrow{F_2=F_2-F_1}\;\;
\left[ 
\begin{array}{ccc|c}
1 & 1 & -1 & 2 \\
0 & -2 & 3 & -2 \\
-1 & 2 & 10 & 1
\end{array} 
\right]
$$

$$
\left[ 
\begin{array}{ccc|c}
1 & 1 & -1 & 2 \\
0 & -2 & 3 & -2 \\
-1 & 2 & 10 & 1
\end{array} 
\right]
\;\;\xrightarrow{F_3=F_3+F_1}\;\;
\left[ 
\begin{array}{ccc|c}
1 & 1 & -1 & 2 \\
0 & -2 & 3 & -2 \\
0 & 3 & 9 & 3
\end{array} 
\right]
$$

$$
\left[ 
\begin{array}{ccc|c}
1 & 1 & -1 & 2 \\
0 & -2 & 3 & -2 \\
0 & 3 & 9 & 3
\end{array} 
\right]
\;\;\xrightarrow{F_2=-\tfrac{1}{2}F_2}\;\;
\left[ 
\begin{array}{ccc|c}
1 & 1 & -1 & 2 \\
0 & 1 & -\frac{3}{2} & 1 \\
0 & 3 & 9 & 3
\end{array} 
\right]
$$

$$
\left[ 
\begin{array}{ccc|c}
1 & 1 & -1 & 2 \\
0 & 1 & -\frac{3}{2} & 1 \\
0 & 3 & 9 & 3
\end{array} 
\right]
\;\;\xrightarrow{F_3=F_3-3F_2}\;\;
\left[ 
\begin{array}{ccc|c}
1 & 1 & -1 & 2 \\
0 & 1 & -\frac{3}{2} & 1 \\
0 & 0 & \frac{27}{2} & 0
\end{array} 
\right]
$$

$$
\left[ 
\begin{array}{ccc|c}
1 & 1 & -1 & 2 \\
0 & 1 & -\frac{3}{2} & 1 \\
0 & 0 & \frac{27}{2} & 0
\end{array} 
\right]
\;\;\xrightarrow{F_3=\tfrac{2}{27}F_3}\;\;
\left[ 
\begin{array}{ccc|c}
1 & 1 & -1 & 2 \\
0 & 1 & -\frac{3}{2} & 1 \\
0 & 0 & 1 & 0
\end{array} 
\right]
$$

$$
\left[ 
\begin{array}{ccc|c}
1 & 1 & -1 & 2 \\
0 & 1 & -\frac{3}{2} & 1 \\
0 & 0 & 1 & 0
\end{array} 
\right]
\;\;\xrightarrow{F_1=F_1-F_2}\;\;
\left[ 
\begin{array}{ccc|c}
1 & 0 & \frac{1}{2} & 1 \\
0 & 1 & -\frac{3}{2} & 1 \\
0 & 0 & 1 & 0
\end{array} 
\right]
$$

$$
\left[ 
\begin{array}{ccc|c}
1 & 0 & \frac{1}{2} & 1 \\
0 & 1 & -\frac{3}{2} & 1 \\
0 & 0 & 1 & 0
\end{array} 
\right]
\;\;\xrightarrow{F_2=F_2+\tfrac{3}{2}F_3}\;\;
\left[ 
\begin{array}{ccc|c}
1 & 0 & \frac{1}{2} & 1 \\
0 & 1 & 0 & 1 \\
0 & 0 & 1 & 0
\end{array} 
\right]
$$

$$
\left[ 
\begin{array}{ccc|c}
1 & 0 & \frac{1}{2} & 1 \\
0 & 1 & 0 & 1 \\
0 & 0 & 1 & 0
\end{array} 
\right]
\;\;\xrightarrow{F_1=F_1-\tfrac{1}{2}F_3}\;\;
\left[ 
\begin{array}{ccc|c}
1 & 0 & 0 & 1 \\
0 & 1 & 0 & 1 \\
0 & 0 & 1 & 0
\end{array} 
\right]
$$

**Solución** 

$$ 
\left[ 
\begin{array}{ccc|c}
1 & 0 & 0 & 1 \\
0 & 1 & 0 & 1 \\
0 & 0 & 1 & 0
\end{array} 
\right]
\implies
\begin{array}{cc|c}
x=1 \\
y=1 \\
z=0
\end{array} 
$$

# C)

A partir de las siguientes matrices:

$$
A =
\begin{bmatrix}
2 & 5 \\
-3 & 4 
\end{bmatrix}
\qquad
B=
\begin{bmatrix}
-1 & 3 \\
6 & -2 
\end{bmatrix}
\qquad
C=
\begin{bmatrix}
1 & 4 & -2 \\
0 & 3 & 5 
\end{bmatrix}
$$

$$
D=
\begin{bmatrix}
3 & -1 \\
2 & 4 \\
0 & 5
\end{bmatrix}
\qquad
E=
\begin{bmatrix}
2 & -1 & 3 \\
0 & 4 & -2 \\
1 & 3 & 5
\end{bmatrix}
$$

Resuelve:

::: panel-tabset

## $A+B$

$$
\begin{bmatrix}
2 & 5 \\
-3 & 4
\end{bmatrix}
+ 
\begin{bmatrix}
-1 & 3 \\
6 & -2
\end{bmatrix}
=
\begin{bmatrix}
2-1 & 5+3 \\
-3+6 & 4-2
\end{bmatrix}
=
\begin{bmatrix}
1 & 8 \\
3 & 2
\end{bmatrix}
$$

## $3A-2B$

$$
3
\begin{bmatrix}
2 & 5 \\
-3 & 4
\end{bmatrix}
-
2
\begin{bmatrix}
-1 & 3 \\
6 & -2
\end{bmatrix}
=
\begin{bmatrix}
6 & 15 \\
-9 & 12
\end{bmatrix}
-
\begin{bmatrix}
-2 & 6 \\
12 & -4
\end{bmatrix}
=
\begin{bmatrix}
6 - (-2) & 15-6 \\
-9-12 & 12 - (-4)
\end{bmatrix}
=
\begin{bmatrix}
8 & 9 \\
-21 & 16
\end{bmatrix}
$$

## $-4B$

$$
-4
\begin{bmatrix}
-1 & 3 \\
6 & -2
\end{bmatrix}
=
\begin{bmatrix}
-4 \cdot -1 & -4 \cdot 3 \\
-4 \cdot 6 & -4 \cdot -2
\end{bmatrix}
=
\begin{bmatrix}
4 & -12 \\
-24 & 8
\end{bmatrix}
$$

## $CD$

$$
C = 
\underbrace{
\begin{bmatrix}
1 & 4 & -2 \\
0 & 3 & 5
\end{bmatrix}}
_{2x3}
; \quad
D = 
\underbrace{
\begin{bmatrix}
3 & -1 \\
2 & 4 \\
0 & 5
\end{bmatrix}}
_{3x2}
$$

La matriz resultante será $2 \times 2$.

-   Fila 1 por columna 1

$$
\begin{pmatrix}
1 & 4 & -2
\end{pmatrix}
\begin{pmatrix}
3 \\
2 \\
0
\end{pmatrix}
=
3+8+0=11
$$

-   Fila 1 por columna 2

$$
\begin{pmatrix}
1 & 4 & -2
\end{pmatrix}
\begin{pmatrix}
-1 \\
4 \\
5
\end{pmatrix}
=
-1+16-10=5
$$

-   Fila 2 por columna 1

$$
\begin{pmatrix}
0 & 3 & 5
\end{pmatrix}
\begin{pmatrix}
3 \\
2 \\
0
\end{pmatrix}
=
0+6+0=6
$$

-   Fila 2 por columna 2

$$
\begin{pmatrix}
0 & 3 & 5
\end{pmatrix}
\begin{pmatrix}
-1 \\
4 \\
5
\end{pmatrix}
=
0+12+25=37
$$

**Resultado $CD$:**
$$
\begin{bmatrix}
11 & 5 \\
6 & 37 
\end{bmatrix}
$$

## $DC$

$$
D = 
\underbrace{
\begin{bmatrix}
3 & -1 \\
2 & 4 \\
0 & 5
\end{bmatrix}}
_{3x2}
; \quad
C = 
\underbrace{
\begin{bmatrix}
1 & 4 & -2 \\
0 & 3 & 5
\end{bmatrix}}
_{2x3}
$$

La matriz resultante será $3 \times 3$.

-   Fila 1 por columna 1: $(3 \cdot 1) + (-1 \cdot 0) = 3+0=3$
-   Fila 1 por columna 2: $(3 \cdot 4) + (-1 \cdot 3) = 12-3=9$
-   Fila 1 por columna 3: $(3 \cdot -2) + (-1 \cdot 5) = -6-5=-11$

-   Fila 2 por columna 1: $(2 \cdot 1) + (4 \cdot 0) = 2+0=2$
-   Fila 2 por columna 2: $(2 \cdot 4) + (4 \cdot 3) = 8+12=20$
-   Fila 2 por columna 3: $(2 \cdot -2) + (4 \cdot 5) = -4+20=16$

-   Fila 3 por columna 1: $(0 \cdot 1) + (5 \cdot 0) = 0+0=0$
-   Fila 3 por columna 2: $(0 \cdot 4) + (5 \cdot 3) = 0+15=15$
-   Fila 3 por columna 3: $(0 \cdot -2) + (5 \cdot 5) = 0+25=25$

**Resultado $DC$:**
$$
\begin{bmatrix}
3 & 9 & -11 \\
2 & 20 & 16 \\
0 & 15 & 25
\end{bmatrix}
$$

:::

# D)

Calcula el determinante de E usando la regla de Sarrus.

$$
|E| =
\begin{vmatrix}
2 & -1 & 3 \\
0 & 4 & -2 \\
1 & 3 & 5
\end{vmatrix}
\begin{array}{cc}
2 & -1 \\
0 & 4 \\
1 & 3
\end{array}
$$

Multiplicamos las diagonales principales y sumamos sus resultados:

$$ (2 \cdot 4 \cdot 5) + (-1 \cdot -2 \cdot 1) + (3 \cdot 0 \cdot 3) = 40 + 2 + 0 = 42 $$

Multiplicamos las diagonales secundarias y restamos sus resultados:
$$ -(3 \cdot 4 \cdot 1) - (2 \cdot -2 \cdot 3) - (-1 \cdot 0 \cdot 5) = -(12) - (-12) - (0) = -12 + 12 - 0 = 0 $$

$$|E| = 42 + 0 = 42$$

# E)

Calcula el determinante de E usando el método de cofactores.

Desarrollamos el cálculo utilizando la primera fila de la matriz $E$:


$$
|E| = 2 \begin{vmatrix} 4 & -2 \\ 3 & 5 \end{vmatrix} - (-1) \begin{vmatrix} 0 & -2 \\ 1 & 5 \end{vmatrix} + 3 \begin{vmatrix} 0 & 4 \\ 1 & 3 \end{vmatrix}
$$

$$
\begin{aligned}
|E| &= 2(4 \cdot 5 - (-2 \cdot 3)) + 1(0 \cdot 5 - (-2 \cdot 1)) + 3(0 \cdot 3 - 4 \cdot 1) \\
|E| &= 2(20 - (-6)) + 1(0 - (-2)) + 3(0 - 4) \\
|E| &= 2(26) + 1(2) + 3(-4) \\
|E| &= 52 + 2 - 12 \\
|E| &= 42
\end{aligned}
$$